language: node_js
node_js:
- "6.11.0"
install: npm install
services:
- postgresql
before_script:
- psql -c 'drop database if exists my_diary;' -U postgres
- psql -c 'create database my_diary;' -U postgres
- npm run createDb
script: npm test
after_success: npm run coverage
